// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNZufUNW-XSBebfuR4c0Pc5CEuK0R9Sqw',
    appId: '1:502267337175:web:6929e2cbf2b99aa5191392',
    messagingSenderId: '502267337175',
    projectId: 'bahanap-cc206',
    authDomain: 'bahanap-cc206.firebaseapp.com',
    databaseURL: 'https://bahanap-cc206-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bahanap-cc206.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqBzsdrfXS595GFY6tHjQmSwxYLIi1s6M',
    appId: '1:502267337175:android:df62a7fc03fb9a3a191392',
    messagingSenderId: '502267337175',
    projectId: 'bahanap-cc206',
    databaseURL: 'https://bahanap-cc206-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bahanap-cc206.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8vwnWtGIs00pfulFCk4ekeqZHtNkw-kg',
    appId: '1:502267337175:ios:8a8c7ce62b583cf9191392',
    messagingSenderId: '502267337175',
    projectId: 'bahanap-cc206',
    databaseURL: 'https://bahanap-cc206-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bahanap-cc206.firebasestorage.app',
    iosBundleId: 'com.example.bahanapAdminApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8vwnWtGIs00pfulFCk4ekeqZHtNkw-kg',
    appId: '1:502267337175:ios:8a8c7ce62b583cf9191392',
    messagingSenderId: '502267337175',
    projectId: 'bahanap-cc206',
    databaseURL: 'https://bahanap-cc206-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bahanap-cc206.firebasestorage.app',
    iosBundleId: 'com.example.bahanapAdminApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNZufUNW-XSBebfuR4c0Pc5CEuK0R9Sqw',
    appId: '1:502267337175:web:acfb8ada9c48ce04191392',
    messagingSenderId: '502267337175',
    projectId: 'bahanap-cc206',
    authDomain: 'bahanap-cc206.firebaseapp.com',
    databaseURL: 'https://bahanap-cc206-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bahanap-cc206.firebasestorage.app',
  );
}
